### ISSUE TITLE
broken site - Twitter - false negative

### ISSUE THREAD

**Issue by mccartney** [WebBreacher/WhatsMyName#161]
Symptoms:
```
$ python3.7 -u ./web_accounts_list_checker.py -s twitter -u WebBreacher
 -  Checking 1 sites
 -  Looking up https://twitter.com/WebBreacher
```

Analysis:

- The Twitter site is broken in non-obvious way.
- It works properly if we do *NOT* specify the Firefox user-agent. So I guess Twitter sees a client presenting itself as a decent browser and expects all fancy Javascripts to work. However if we came with a simple client (Python Requests) it serves the content properly.
- So typically we use the user-agent of Firefox to fool all the services. Twitter doesn't need to be fooled. And actually shouldn't be fooled.

**Comment by WebBreacher** [comment]
Interesting and thanks for finding this. I've been wondering about the UserAgent submission and whether it is helping to pretend to be a normal browser instead of Python. My preference would be to find some page that would validate the user account existence without having to make adjustments per site to the User Agent as, again, this JSON file is used in other scripts. Perhaps we could use something like the mobile interface (https://mobile.twitter.com/WebBreacher/), user's avatar existence (https://twitter.com/WebBreacher/photo), or header photo (https://twitter.com/WebBreacher/header_photo).

**Comment by mccartney** [comment]
I couldn't find any alternate URL endpoint which would handle Firefox user-agent. None of the ones you have suggested seem to do the job.
We need a better trick.
I agree adding the logic to use different user-agents for some sites is a complexity I think we should avoid.

**Comment by WebBreacher** [comment]
disabled in #181

**Comment by WebBreacher** [comment]
#174 discusses this too. Wondering if we should be using no UA by default and then turn on that option per site.

**Comment by WebBreacher** [comment]
fixed this using a different site.
