### ISSUE TITLE
Music Sites for Consideration

### ISSUE THREAD

**Issue by baywolf88** [WebBreacher/WhatsMyName#224]
Site - Artist - Artist Link

audius.com - Zunapalooza -  (https://audius.co/zunapalooza)
music.yandex.com - BTS -  (https://music.yandex.com/artist/3942411)
Anghami.com - BTS -  (https://play.anghami.com/artist/1920606/5)
Tidal - Baywolfmusic - (https://listen.tidal.com/artist/22046297)
Deezer.com - Baywolfmusic - (https://www.deezer.com/us/artist/112402842)
iheart.com - Rick Astley - (https://www.iheart.com/artist/rick-astley-118093/)
kkbox.com - BTS - (https://www.kkbox.com/tw/en/artist/MHIoDqhxn5YNry0F0AVbQ08K-index-1.html)
us.napster.com - BTS - (https://us.napster.com/artist/bts)
music.163.com (NetEase Music) - BTS - (https://music.163.com/#/artist?id=783124)
jiosaavn.com (saavn) - Foo Fighters - (https://www.jiosaavn.com/artist/foo-fighters/HH6Mx1ruC6s_)

**Comment by WebBreacher** [comment]
Thank you for the submission. Since the tool takes a username as input and many of these sites convert usernames into numbers, we cannot use most of these. For the site to work in WMN, kwe need the username in the url like `https://twitter.com/name`.  Alternatively, if we can send a URL like `https://example.com/search/name` and it retrieve the single result for the username, that would work. 

In general, the username should appear in the URL. We will look at these URLs and see what we can do.

**Comment by WebBreacher** [comment]
we have researched these and included as many as possible in the project. thanks!
