### ISSUE TITLE
Create new Python checker script

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#430]
I'd like to start fresh with a new Python checker script for us in the project. It'd be used:

1. For us to check if the detection strings and user accounts for a given site are correct.
2. For people wanting to use a light-weight Python checker to search for a username(s)

### General
Python 3.x (any library used should be installable from pip)

###  Inputs
1. Issue #414 was just implemented so this script should be written to only be used with the newer `wmn-data.json` file and not the older/current one.
1.  If run without username or site name, script checks all the sites against each site's `known` values (checking them all for each site).
2.  If run with a username and no site name, that username is used to substitute for the {account} in every `uri_check` URL
3.  If a site name ("name" in JSON) is entered with a username, then only that site is checked using that user-supplied username
4.  If a site name is submitted with no username, then the `known_accounts` values are used to check the accuracy of the site entry.  

### Outputs
1. Script always outputs results to screen/terminal  
2. Screen output is colorized and easy to read
3. Screen output should show some kind of progress meter or status while sites are being checked.
4. Output to text file and/or screen should be a table and look like `site name | url | category | result`
5. The script always creates a text file with the results. Filename for this file should reflect the date-time-username like `20220716-1201-webbreacher` so that multiple runs of the tool will output to different files.
6.  If username is submitted, text file with the username in file name is created with output.
7.  Options to output to CSV

### Additional requirements
1.  The `uri_check` is used to check if a username is found on a site. The `uri_pretty` is used to point to where that profile might be. Some sites (twitter.com, instagram.com, etc.) do not work well with the tool BUT 3rd party sites do. So sometimes we check the 3rd party site and then show the other site has the account. So, if the `uri_check` is checked and there is a positive result, display the `uri_pretty` location
2.  When run, the script should skip any entries that have the `valid` parameter set to false
3.  Option to only use a certain category of sites (JSON `cat` value)  
4.  Threaded checking of sites
5.  Option to have script follow redirects (HTTP response code 30x)
8.  If the `uri_check` inserts the username into the subdomain (Ex. username.blogger.com), only allow usernames that are alphanumeric to be checked. Those with periods, hyphens and other non-alphanumeric characters are skipped.  
9. To address issue #55, if the username has a `.` in it, sites that insert the username into the subdomain should be skipped. So any site that has a `uri_check` like `"https://(account).example.com"`  should be skipped for accounts with `.` in them.

### Options/Flags
1.  Option to use a recent Firefox or Chrome UserAgent for the request instead of the Python one Requests module uses.
2.  Option for user to supply their own JSON file to use for the checks instead of the JSON file that ships with the project
3.  Option to reveal the HTTP Response code and body so that we can debug.
4.  Default timeout value for Request should be 30 seconds. Add option to change that via CLI value
5.  Option to give the script a list of usernames to check which it would iterate over.
6. Option to output to CSV (noted above)
7. Option to output to a specific file name

Looking for someone with excellent Python coding skills to make this from scratch (not based off our existing scripts).

**Comment by WebBreacher** [comment]
Altered issue wording using parameters consistent with #414

**Comment by yooper** [comment]
To provide these enhancements via CLI, would you be open to using an off the shelf python CLI library such as:

- https://github.com/pallets/click
- https://github.com/python-poetry/cleo (my goto)

I don't mind doing the implementation piece, I just do not want to re-invent the wheel with parsing input from the CLI the hard way. 

Also, would you be interested in leveraging async/threading functionality for performing http requests to get more throughput when scanning large sets of web sites?

**Comment by WebBreacher** [comment]
@yooper 

1. Yes to the async threading (see Additional requirements, bullet 4 above) 
2. I'm not looking for an interactive CLI here just `python whatsmyname.py -u webbreacher -i inputfile.json -o outfile.txt`. Of course the colorization of the text output and other features of _cleo_ above seem to also meet some needs.

**Comment by yooper** [comment]
@WebBreacher , 
Do you want the async threading work built on top of the branch "new-python-script" or "main" ?

Sounds good on the CLI for now. 
Cheers,

**Comment by WebBreacher** [comment]
This issue is an ask for the entire new checker script to replace the existing two and having all the above features not just the async calls). 

That brach was created for this work.

**Comment by yooper** [comment]
Sorry, for blasting you with questions.. I need to get a good understanding of what you need done so I don't start down the wrong path. 

With the new checker scripts are you fine with moving to a more modular approach so its easier to write unit tests against the functionality? 

Do you want docker support baked in for testing against multiple versions of python?

**Comment by WebBreacher** [comment]
> With the new checker scripts are you fine with moving to a more modular approach so its easier to write unit tests against the functionality?
**Yes**

> Re: Docker
**No**

**Comment by yooper** [comment]
@WebBreacher , here is a current break down of the refactor.

#### Outputs

- Script always outputs results to screen/terminal **Done, the format of the outputted data is dependent on the format selected, by default, its json.**
- Screen output is colorized and easy to read **Not Done**
- Screen output should show some kind of progress meter or status while sites are being checked.  **Won't implement, it only takes a couple seconds to run, now that the program is multithreaded.**
- Output to text file and/or screen should be a table and look like site name | url | category | result **Mostly Done, current outputs are generated url, response http status code, (optional) response content, browser agent used.**
- The script always creates a text file with the results. Filename for this file should reflect the date-time-username like 20220716-1201-webbreacher so that multiple runs of the tool will output to different files. **Mostly Done, defaults to outputting to a new temporary file per run**
- If username is submitted, text file with the username in file name is created with output.
Options to output to CSV **Done, the end user can input the name of the outputted file and the file format**

#### Additional requirements
- The uri_check is used to check if a username is found on a site. The uri_pretty is used to point to where that profile might be. **The field `generated_uri` is used to capture the URL used for testing if a user exists on a site. Only sites that return a successful http status code are displayed to the end user by default.** 
 - Some sites (twitter.com, instagram.com, etc.) do not work well with the tool BUT 3rd party sites do. So sometimes we check the 3rd party site and then show the other site has the account. So, if the uri_check is checked and there is a positive result, display the uri_pretty location **See previous answer** 
- When run, the script should skip any entries that have the valid parameter set to false **Done**
- Option to only use a certain category of sites (JSON cat value) **Done, I changed the parameter from "cat" to "category" to reduce confusion."
- Threaded checking of sites **Done, works really fast now**
- Option to have script follow redirects (HTTP response code 30x) **Done, by default this is off. If turned on, it will follow up to 10 redirects. The number of redirects followed is configurable**
- If the uri_check inserts the username into the subdomain (Ex. username.blogger.com), only allow usernames that are alphanumeric to be checked. Those with periods, hyphens and other non-alphanumeric characters are skipped. **Not Done**
- To address issue https://github.com/WebBreacher/WhatsMyName/issues/55, if the username has a . in it, sites that insert the username into the subdomain should be skipped. So any site that has a uri_check like "https://(account).example.com" should be skipped for accounts with . in them **Done**

#### Options/Flags
- Option to use a recent Firefox or Chrome UserAgent for the request instead of the Python one Requests module uses. **Done**
- Option for user to supply their own JSON file to use for the checks instead of the JSON file that ships with the project **Needs further discussion**
- Option to reveal the HTTP Response code and body so that we can debug. **Done**
- Default timeout value for Request should be 30 seconds. Add option to change that via CLI value **Done and configurable for total time the program is running and individual connect requests to web sites is are open**
- Option to give the script a list of usernames to check which it would iterate over. **Done**
- Option to output to CSV (noted above) **Done**
- Option to output to a specific file name **Done**

#### Extras
- Built into pypi package, https://pypi.org/project/what-is-my-name/
- Added unit tests, have 90% coverage
- Working on additional documentation for running from the command line.
- Current state of refactor can be found here, https://github.com/yooper/WhatsMyName/tree/threaded_approach

**Comment by WebBreacher** [comment]
HOLY COW! Thank you @yooper

**Comment by WebBreacher** [comment]
Met with @yooper to get status. Estimated having a usable script in the coming week.

**Comment by WebBreacher** [comment]
Thanks to @yooper for #513 which addresses these issues.

**Comment by WebBreacher** [comment]
Closing this issue as the script has been merged with the main branch and is in operation. New feature/bug requests will be their own issues.

# HUGE THANKS TO @yooper for this work!
