### ISSUE TITLE
megamodels.pl false positive

### ISSUE THREAD

**Issue by crjeder** [WebBreacher/WhatsMyName#437]
megamodels.pl cuts of the username at the first dot "." e. g.
`mr.smith@gmail.com`
and
`mr.miller@gmail.com`
are the same account with the name `mr`

**Comment by WebBreacher** [comment]
Also, it does not look like this site uses email addresses for their usernames.

**Comment by crjeder** [comment]
Both of your statements are correct. But if you search for e. g. `mr.smith` and an account named `mr` exists you get false positives. You might want check for those cases if you want to avoid false positives.
I was running into that checking e-mail based username (which a lot of sites use).

**Comment by WebBreacher** [comment]
Understood. This would need to be a check outside of our JSON file since the tool would need to look for specific markers for a specific username entered. Right now, we look for only "is a certain piece of text found in the response from the server". It has to be generic text since a user of `mr.smith` might not actually have trhe text `mr.smith` on the response page. Their profile name might be `mister smith`. 

At its core, WhatsMyName focuses on "could there be an account on that platform?" and provides a Boolean true/false result. Ultimately the script writers and analysts using our JSON file need to code or manually verify the results.
