### ISSUE TITLE
Add "encoding='utf-8'" in line 16 of "file_extractors.py" (for Windows)

### ISSUE THREAD

**Issue by JD777777777** [WebBreacher/WhatsMyName#667]
This took me some time to work out.
Windows without a special option for python or a set PYTHONUTF8=1 in the environment will default to CP-1252, which will fail miserably with the current JSON input file.

To spare other Windows user the pain of having to research this for themselves, line 16 of "file_extractors.py" could be changed:
FROM: with open(file_path) as json_file:
TO:      with open(file_path, encoding='utf-8') as json_file:

**Comment by WebBreacher** [comment]
@yooper  should we make a change in the script?

**Comment by yooper** [comment]
@JD777777777 , thanks for your input. I will investigate further. Can you provide what version of python you are using. Thank you.

**Comment by JD777777777** [comment]
It's Python 3.11.1.
For the sake of completeness, this is the errors I got:

C:\bin\PYTHON\WhatsMyName-main>python whats_my_name.py -u yooper
Traceback (most recent call last):
  File "C:\bin\PYTHON\WhatsMyName-main\whats_my_name.py", line 6, in <module>
    check_for_presence()
  File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\main.py", line 45, in check_for_presence
    asyncio.run(start_check_for_presence())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\main.py", line 21, in start_check_for_presence
    sites: List[SiteSchema] = await process_cli(cli_options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\app\tasks\process.py", line 111, in process_cli
    sites = generate_username_sites(cli_options.usernames, get_sites_list(cli_options))
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\app\tasks\process.py", line 27, in get_sites_list
    sites: List[SiteSchema] = site_file_extractor(cli_options.input_file)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\app\extractors\file_extractors.py", line 16, in site_file_extractor
    json_data = json.load(json_file)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1583: character maps to <undefined>

**Comment by JD777777777** [comment]
> C:\bin\PYTHON\WhatsMyName-main>python whats_my_name.py -u yooper
Traceback (most recent call last):
File "C:\bin\PYTHON\WhatsMyName-main\whats_my_name.py", line 6, in
check_for_presence()
File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\main.py", line 45, in check_for_presence
asyncio.run(start_check_for_presence())
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
return self.loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\main.py", line 21, in start_check_for_presence
sites: List[SiteSchema] = await process_cli(cli_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\app\tasks\process.py", line 111, in process_cli
sites = generate_username_sites(cli_options.usernames, get_sites_list(cli_options))
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\app\tasks\process.py", line 27, in get_sites_list
sites: List[SiteSchema] = site_file_extractor(cli_options.input_file)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\bin\PYTHON\WhatsMyName-main\whatsmyname\app\extractors\file_extractors.py", line 16, in site_file_extractor
json_data = json.load(json_file)
^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\json_init.py", line 293, in load
return loads(fp.read(),
^^^^^^^^^
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1583: character maps to

**Comment by downerboy** [comment]
mojibake:

A must read for every developer:  [](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/)

I have a countered this too many times working with and developing service layer architecture for placing mainframes and modernizing other systems. and modernizing other systems.

many times service calls are being sent data via XML and whoever wrote the Scammer for the message format was not aware that XML is strictly UTF-8 and too many times I've had to delete the attribute tag saying this code page is UTF 16 or something else, but it breaks it because XML is strictly UTF-8 HTML is an extension of XML and therefore the clearing information is coming across in the code page. Other than UTF-8 is not going to work. Many services and endpoints just assume the data coming in this UTF-8 and another problem with that is those services may be developed using a language that that is assumed to be using Unicode and isn't, I think PHP ran into this problem. I don't know if it was resolved or not I didn't work with PHP so I don't trust me on what I'm saying that the vet it out yourself before repeating it.

Also, I know a lot of relational database systems. If you do not explicitly state what the code page is going to be for that database it defaults to the code page the server is running on, and it still flabbergast me that DBAs don't change the code page to Unicode, and just leave it to the default and then wonder why everything breaks when they have to migrate that database to a newer machine because the database is running on an OS that is now deprecated. I'm not leaving them at the mercy of the server architecture and this becomes a real problem for systems that run over a long period of time like the university of California. Were they have data retain from the 80s and are trying to process it with multiple endpoints till it gets to the client and each in service running on a different system and the developer only knows the API for the service and not the underlying architecture.

For example, a how to fix a driver for and the developer only knows the API for the service and not the underlying architecture.

For example, a how to fix a driver used for power builder seven applications two submit data to a cobalt David, which would send that to a main frame and then that main frame would send the information back to the driver which would send that data to a WCF service, which would then be pumped into a Microsoft SQL server database . When opening up the schema definition, the header attribute to UTF-16 as the codepage XML is strictly UTF-8.  each email is an extension of XML so HTML is strictly UTF-8 unless things have changed in the past few years. I have lost my eyesight so staying on top of things has been very difficult and explains why there's probably going be weird, typos, odd words. Grammatical, errors in my response because I'm using speech to text and iOS and I thought with the advent of Siri speech to text/text to speech would improve quickly and nicely; no, if anything, it is much worse, so please bear with me here.

Back to topic, the driver was written in C++ and using character calls for non-window systems like for Linux, and what not and at the time C++ for windows using the windows libraries provided with the OS used a different function for handling characters and strings in the likes if I remember correctly, which were presented with W, and this driver was using calls from non-Windows libraries, and so it would get the data in and then pass it on to WCF services which is process it and feed into Microsoft SQL servers. WCF written in.net assumes the characters are using UCF 16 little Indian.(I hope it's spelled Indian correctly, and not Indian) so there's characters going across the wire coming from a cobalt main frame, being perceived as UTF-8, and processed by whatever code page, the non-Windows character pot, parsing library, that was being used which was not the ISO 1859–16 and eventually the results would end up in a Microsoft SQL database, running on a Windows server where are the code pages are changing now, and then, whenever the machine will change, or the OS would change, because the DBAs were not explicitly specifying the database to use Unicode, and with Microsoft SQL server, at least back, then, default it to the code page of the server. If you did not explicitly specify the code page, and unlike other Microsoft products, I've used to where the configuration by default comes out to be in your best interest and secure as best as possible. This was not the case for their SQL server solutions, and that code page was inconsistent because it was a server farm, and it was such a silly little thing which pretty much almost stop the project from going further or being completed, and I was being operated by a team of people PhD's who had forgotten the very first thing they probably learned and CS 101 it difference between UNI code Anansi and what the heck a code page is.

before going blind and losing my career, I developed a habit of assuming that any information coming in was bad and treat it as such and would run it through the appropriate tools provided by the appropriate framework. Did you get everything taking in UTF-8 and spitting out UTF-8 while maintaining the fidelity of the data to this day you'll still find a Lotta stuff is using windows CP 12 5Q without any configuration or any of the provided behaviors of the tool you're using to get all communications on Unicode to UTF-8.

I think reading the article above will probably make more sense than what I just spoke into my phone and I hope this helps and I hope this isn't redundant. It's very hard for me to discern between things due to my vision and the lack of useful meta-data necessary to make an application truly accessible by anything.

**Comment by janbinx** [comment]
I had the same issue. I've added a pull request for this to be fixed, as per https://github.com/WebBreacher/WhatsMyName/pull/700

**Comment by WebBreacher** [comment]
Closing this as the script is no longer part of this project.
