### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by Sector035** [WebBreacher/WhatsMyName#696]
I tested using VPN's and mobile hotspots, but the results seem to be inconsistent. Using Python 3.9.15, updated pip, fresh clone from GitHub, using the yooper-script, running in pyenv.

When connecting directly to a fast connection (fibre), and targeting a specific category (like social), the results are stable and correct.

![2311-whatsmyname](https://user-images.githubusercontent.com/47351205/226262391-441e9e91-42d5-48d2-a626-bed2101d3a1c.jpg)

**Comment by WebBreacher** [comment]
Thanks for submitting this issue and this is a known issue with how tools like this work. I'll explain more below.

1. They are at the mercy of how websites respond to requests. So, if a website blocks requests from Python tools, you will not get a result. If a website pops up a CAPTCHA when you use a VPN, you will not get results. it is a function of how those destination sites work and not our tool. 
2. If you run a WMN scan using the web interface (https://whatsmyname.app), you will see some sites have CSP (https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) enabled to block one site's scripts from accessing its content. That gives potential false positives and negatives.
3. When you run the script multiple times against the same hosts, the websites may think you are a "bot" (which you are) and prompt for you to solve a CAPTCHA or check your client for JavaScript capabilities...both will fail using the Python tool. Wait a little bit and the site may reset your access and let you back in without having to pass a "human" test. This is out of our control.
3. We suggest using multiple tools (Python, web, manual) to perform a complete username search so as to minimize the impacts of these security features that websites deploy.
4. While we could try to implement things like CAPTCHA-solving and proxy use in our tools, we leave those techniques up the end users.
5. We are working on a project to better explain which sites will be accessible via what tool and connection mechanism but it is weeks/months off.

Hoping this helps.

**Comment by Gowixx** [comment]
@WebBreacher you could help lessen the chance of this by using libraries. E.x tls_client helps spoof correct data on each request, lots of the time, bypassing cloudflare, and other anti-bot services

**Comment by WebBreacher** [comment]
@Gowixx from a cursory look (and please correct me here), it looks like that library merely rotates through a bunch of UserAgents and does not do anything with JavaScript or CAPTCHAs. The current script has a mechanism to do this (see the values in https://github.com/WebBreacher/WhatsMyName/blob/main/whatsmyname/app/resources/user-agents.json). 

To move this simple checker to a more robust one, we would need to launch a headless browser which would then help us pass JS checks and header information checks more easily. But there is a huge cost in time and resources for this. We tried doing this in a lab and the starting up and shutting down over 600 headless Chrome clients and the time taken to pass the JS tests made this an unworkable solution for a free, open source script.

I mention the free/openness here because, with funding, you can do the things necessary to seem like a normal web browser to websites. It just is not free and not something we can afford in this script.

**Comment by Gowixx** [comment]
This library is more for spoofing legit browsers. It spoofs ciphers and order of requests. This makes the requests look 1:1 with the ones browsers make. Sites like cloudflare easily detect invalid browsers as "Trying to spoof legitimate device."

Not sure if that made sense to you, if not, I can rephrase it

**Comment by WebBreacher** [comment]
Closing this as the script is no longer part of this project.
