### ISSUE TITLE
Project Modification: Suggestion to change "name" to "domain"

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#843]
@Itsoon brought up that the contents of the `name` field in the JSON are all over the place as far as spaces, case, and format. Sometimes we use the domain, other times we use the name of the website/service as they display on their site.

The suggested course of action would be to rename every entry to be the `uri_pretty` or, if that is not there, the `uri_check` domain. 

For some of the sites, it is not a big deal and actually clarifies the entry a bit like with:
- "name" : "3DNews" -> "domain" : "forum.3dnews.tech"
- "name" : "35photo" -> "domain" : "35photo.pro"

For other sites, we would lose the "function" of what the domain hosts like these:
- "name" : "Mastodon-101010.pl" -> "domain" : "101010.pl" (lose the "Mastodon info"
- "name" : "Climatejustice.rocks (Mastodon Instance)" -> "domain" : "climatejustice.rocks"

I think these are more exceptions than the rule and for the vast majority of the entries, changing to the domain would be helpful.

If we wanted, we could keep the `name` field and just add a `domain` field for now and transition to only `domain` use in the future.

Tagging some of our downstream developers for comment.
@bcoles @yooper @C3n7ral051nt4g3ncy @grabowskiadrian  @p1ngul1n0 @kpcyrd

**Comment by yooper** [comment]
Typically a 'name' field represents a unique identifier for each record in
the data set. I am for KEEPING the name field and if the user needs to
determine the domain, then parse domain from the record's given URL using a
script at runtime. The less data we have in each record the better, because
it adds complexity when creating and maintaining the data set.

I can readily commit to any route that you decide on.

**Comment by WebBreacher** [comment]
Thanks @yooper. The `name` field/element would still be unique as it'd be the domain plus the server. So instead of `3dnews.tech` it'd be `forum.3dnews.tech` which would have to be unique amongst other "sites" in the project.

**Comment by Itsoon** [comment]
Because performance is a key point for me, I think it's better to include the domain directly in the JSON file. This reduces the computational overhead when accessing the data, as the domains are already calculated and available, speeding up processing. 

And to facilitate management and updating of the JSON file, small Python scripts can be used. To minimize manual tasks

**Comment by yooper** [comment]
@Itsoon , the I/O cost to make the call to the given site to check the username takes significantly more time than computing the domain from a given Url. I/O is your bottleneck when it comes to performance.

**Comment by Itsoon** [comment]
Sure, but it's impossible to reduce the time it takes to call the site to verify a username, so let's reduce what's under our control.
After that, if it really bothers you, no problem. The tools will be able to make the change themselves on first launch.

**Comment by p1ngul1n0** [comment]
Hi guys,

I believe we should keep the `"name"` property as it is and address any issues with sites currently using the domain in this property. Adding a `"domain"` property, as @yooper mentioned, would create additional maintenance work without providing significant benefits at this time (IMO).

**Comment by WebBreacher** [comment]
Based on the discussion here, I cannot see changing the WMN JSON to replace the `name` element with `domain` at this time. As for adding another element for `domain`, I agree with the above notes that extracting the domain from the `uri_check` or `uri_pretty` should not be that intensive an operation for modern systems to handle if desired.

So, for now, we will not be changing WMN to address this issue.
